on: [push, pull_request]
name: Konstruktoid ShellCheck
jobs:
  konstruktoidShellCheck:
    name: Konstruktoid ShellCheck
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Konstruktoid ShellCheck
        uses: ./action-shellcheck
      - name: Create Issue
        if: failure()
        uses: JasonEtco/create-an-issue@main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
