on: [push, pull_request]
name: ShellCheck

permissions:
  contents: read

jobs:
  konstruktoidShellCheck:
    name: ShellCheck
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3.6.0
      - name: Konstruktoid ShellCheck
        uses: ./action-shellcheck
